version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080
        VITE_GOOGLE_MAPS_API_KEY: AIzaSyB6yKm_vZw2nCWECG9Ju_Ytg2i19W3L96s
    container_name: maltan-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - maltan-network

networks:
  maltan-network:
    driver: bridge

